apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod1
  labels:
    coreName: nginx-pods-label
    app: nginx-app
spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 80
