apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-replicaset1
  labels:
    name: nginx-replica-label
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-label
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx-label
    spec:
      containers:
        - name: nginx-container
          image: nginx
          ports:
            - containerPort: 80