apiVersion: v1
kind: Service
metadata:
  name: consul
  namespace: consul
spec:
  ports:
    - name: http
      port: 8500
      targetPort: 8500
    - name: serf
      port: 8301
      targetPort: 8301
    - name: serf-wan
      port: 8302
      targetPort: 8302
    - name: server
      port: 8300
      targetPort: 8300
  selector:
    app: consul
  clusterIP: None